+f
SFUAnime/Ren pull request #128
Opened 2018-10-23 21:33 UTC by zach1502

My condolences Injabie.

#125

### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
+f

2018-10-23 21:43 UTC, zach1502 commented
F

2018-10-23 21:43 UTC, zach1502 commented
F

2018-10-23 21:43 UTC, zach1502 commented
hiteler

2018-10-24 18:56 UTC, Injabie3 requested changes

2018-10-24 18:56 UTC, Injabie3 commented on cogs/Respects.py
> +
Where is the cog set up?

2018-10-24 18:56 UTC, Injabie3 commented on cogs/Respects.py
> +    async def mycom(self, context):
This does not address #125.

2018-10-25 21:00 UTC, zach1502 commented on cogs/Respects.py
> +    async def mycom(self, context):
dont worry, i got this

2018-11-05 23:27 UTC, Injabie3 requested changes
Hey zach, please see some comments below.

2018-11-05 23:27 UTC, Injabie3 commented on cogs/Respects.py
> +        who_F.append(ctx + ", ")
Did you mean`ctx.message.author`?

2018-11-05 23:27 UTC, Injabie3 commented on cogs/Respects.py
> +        who_F = []
This is the right idea: we want a list of people who have reacted.  The next step is to figure out how to store this across multiple invocations of this command.  Off the top of my head, we'll probably want a helper function to do some kind of a lookup to see when the latest invocation was, and if it exceeds, then we want a new "has paid respects", else append to the old one, delete the pre-existing "respects", and put a new one.

2018-11-05 23:27 UTC, Injabie3 commented on cogs/Respects.py
> +        await asyncio.sleep(10)
This sleep seems unnecessary.  We don't need to wait 10 seconds for this function, multiple users can still invoke this function from a channel anyways.

2018-11-05 23:27 UTC, Injabie3 commented on cogs/Respects.py
> +        who_F = []
Right now, this is only local to each invocation of the command, we want this to exist over multiple invocations.

2018-11-22 18:26 UTC, Injabie3 commented
As per our discussion, you could do something like the following:
1. Someone invokes command.
2. See where it comes from (e.g. from what server and channel)
3. Do a lookup to see when the last invocation of that was (this you have to make, e.g. a dictionary with perhaps a nested key with server and channel IDs).  Two cases: there was a previous invocation or there wasn't.
4. If there was no invocation, just send the message with who has paid respects AND save the message ID, and save who has paid respects, the message ID, and the invocation time to the lookup.
5. If there was, check the time, and see if it's within a threshold (you determine).  If the time has passed, create a new one.  Else just delete the previous message and make a new one in the same manner as above.

This is just a rough guide from the idea I was thinking of on the back of some rough paper, perhaps you may find a better approach.

2018-12-17 00:21 UTC, Injabie3 commented
Don't see anything happening lately with this PR, so I will try something out.

2018-12-18 08:30 UTC, Injabie3 commented
Closing for #154 merged in at commit 7a60cec2e3aa919ae966dc49f9daf06cd56fabf3.

2018-12-18 08:30 UTC, closed without merging