[Triggered] Migrate To V3
SFUAnime/Ren pull request #350
Opened 2021-01-30 07:35 UTC by jlacsamana

### Type

- [x ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
Ported Over Triggered cog from V2, and added support for use on the Windows OS

2021-01-30 07:54 UTC, Injabie3 requested changes
Overall LGTM, will let @KaguneAstra take another scan :)

2021-01-30 07:54 UTC, Injabie3 commented on cogs/triggered/triggered.py
> +SAVE_FILE = "settings.json"
Can we remove these unused constants?

2021-01-30 07:54 UTC, Injabie3 commented on cogs/triggered/triggered.py
> +
Should be safe to remove this code block since we're not using it in v3 anymore.

2021-01-30 07:54 UTC, Injabie3 commented on cogs/triggered/triggered.py
> +#     bot.add_cog(customCog)
Can remove this v2 setup code since we're not using it anymore

2021-01-30 10:00 UTC, jlacsamana commented
the new commands are potentially as irritating as that now spoiler tagged renjam command, please exercise caution with allowing user access to the full suite of triggered commands.

2021-01-30 20:00 UTC, Injabie3 reviewed
Had some breakfast thoughts on this, feel free to ignore them.

2021-01-30 20:00 UTC, Injabie3 commented on cogs/triggered/triggered.py
> +        hyper: bool
Just a thought while I was eating breakfast, what are your thoughts on making `deepFry` and `hyper` an optional keyword argument like `mode`, and it takes in either "deepfry" or "hyper"? That way, when we use it above we'll know what it is without having to dive to the method definition to see which bool maps to hyper or deepfry. Would require changing the method to fix the bool stuff.
```suggestion
    async def _createTrigger(self, user: discord.Member, mode: str = None):
        """Fetches the user's avatar, and creates a triggered GIF
        
        Parameters:
        -----------
        user: discord.Member
        mode: Optional[str]
            One of the following: "hyper", "deepfry".
```

2021-01-30 20:00 UTC, Injabie3 commented on cogs/triggered/triggered.py
> +            savePath = await self._createTrigger(user, False, False)
As an example, this would become
```py
            savePath = await self._createTrigger(user)
```

2021-01-30 20:00 UTC, Injabie3 commented on cogs/triggered/triggered.py
> +            savePath = await self._createTrigger(user, False, True)
As an example, this would become
```py
            savePath = await self._createTrigger(user, mode="hyper")
```

2021-01-30 20:00 UTC, Injabie3 commented on cogs/triggered/triggered.py
> +            savePath = await self._createTrigger(user, True, False)
As an example, this would become
```py
            savePath = await self._createTrigger(user, mode="deepfry")
```

2021-01-30 21:01 UTC, KaguneAstra approved these changes

2021-01-30 21:01 UTC, KaguneAstra commented on cogs/triggered/triggered.py
> +        """Are you triggered? Say no more."""
Nit: Change doc string to reflect being hyper triggered

2021-01-30 21:01 UTC, KaguneAstra commented on cogs/triggered/triggered.py
> +        """Are you triggered? Say no more."""
Same nit as above

2021-01-30 23:18 UTC, Injabie3 approved these changes

2021-01-31 04:22 UTC, Injabie3 approved these changes

2021-01-31 06:49 UTC, merged