Waifupics
SFUAnime/Ren pull request #387
Opened 2021-05-17 21:28 UTC by LPlamondon

### Type

- [ ] Bugfix
- [ X ] Enhancement
- [ ] New feature

### Description of the changes
Added support for the catgirls cog to make use of waifu.pics sfw/neko. Admins can toggle the use of this

2021-05-18 01:33 UTC, Injabie3 requested changes
Thanks! Overall LGTM. What are your thoughts on handling HTTP exceptions for the waifupic api? Maybe if we get an exception, we can fall back to local ones?

note to self: can look into aiohttp later since requests might  be blocking.

2021-05-18 01:33 UTC, Injabie3 commented on cogs/catgirl/catgirl.py
> +def getImageUrl(image):
can we add a docstring to this, similar to the one in `getImage`?

(in retrospect I realize how poorly I named the original one)

2021-05-18 01:33 UTC, Injabie3 commented on cogs/catgirl/catgirl.py
> +    @checks.admin_or_permissions(manage_guild=True)
let's set this to mods and above.
```suggestion
    @checks.mod_or_permissions(manage_guild=True)
```

2021-05-18 01:33 UTC, Injabie3 commented on cogs/catgirl/catgirl.py
> +        if nekoToggle == True:
```suggestion
        if nekoToggle:
```

2021-05-18 01:33 UTC, Injabie3 commented on cogs/catgirl/catgirl.py
> +                URL = "https://api.waifu.pics/sfw/neko"
nit: can you put this constant at the top with the rest of the constants?

2021-05-18 01:33 UTC, Injabie3 commented on .gitignore
> +core/settings.json
can we remove the gitignore changes? cog configs shouldn't be within the source tree anyways.

2021-05-18 03:35 UTC, LPlamondon commented on cogs/catgirl/catgirl.py
> +def getImageUrl(image):
Added the docstring as requested

2021-05-18 03:36 UTC, LPlamondon commented on cogs/catgirl/catgirl.py
> +                URL = "https://api.waifu.pics/sfw/neko"
Moved it up top with the other constants

2021-05-19 03:05 UTC, Injabie3 requested changes
Fix it, then Ship it!

2021-05-19 03:05 UTC, Injabie3 commented on cogs/catgirl/catgirl.py
> +                #
empty comment? probably can remove.

2021-05-19 03:05 UTC, Injabie3 commented on cogs/catgirl/catgirl.py
> +def getImageUrl(image):
Can you please move this docstring underneath the function declaration, similar to how it's done elsewhere? For context, docstrings show up if you do `.__doc__` on the function.

2021-05-19 03:10 UTC, LPlamondon commented on cogs/catgirl/catgirl.py
> +                #
Removed

2021-05-19 03:11 UTC, LPlamondon commented on cogs/catgirl/catgirl.py
> +def getImageUrl(image):
Moved it underneath. Sorry about that

2021-05-19 03:12 UTC, Injabie3 approved these changes

2021-05-20 05:50 UTC, merged