Thomas dev
SFUAnime/Ren pull request #433
Opened 2021-07-05 03:06 UTC by tplamondon

Fixed source cog by adjusting the code to use the newest version of tracemoepy since trace.moe updated their api. This will require updating ren's version of tracemoepy.

If you use pip, I think you can update it by running "pip install --upgrade tracemoepy"

2021-07-05 04:43 UTC, Injabie3 reviewed
Thanks, changes LGTM.

One other thing, I see we're using non-async version here, can we switch to using the [async](https://github.com/DragSama/tracemoepy/tree/v4.1#asyncio) version instead? 

Note to self: [Tag v4.1](https://github.com/DragSama/tracemoepy/releases/tag/v4.1) is major change wrt `result.docs` -> `result.result`.

2021-07-05 04:59 UTC, tplamondon commented
> 
> 
> Thanks, changes LGTM.
> 
> One other thing, I see we're using non-async version here, can we switch to using the [async](https://github.com/DragSama/tracemoepy/tree/v4.1#asyncio) version instead?
> 
> Note to self: [Tag v4.1](https://github.com/DragSama/tracemoepy/releases/tag/v4.1) is major change wrt `result.docs` -> `result.result`.

This should be done now

2021-07-05 05:17 UTC, quachtridat commented
I believe the point of `aio_session` (`aiohttp.ClientSession`) is that you could have one instance of it for the entire cog and not every time the function gets invoked.

Could we have the `Source` initializes an instance of `tracemoepy.AsyncTrace` as an instance field and respective methods would use that instance to do the job? Also this way we would have to close the `aio_session` on unload. Check cog `Heartbeat` for reference (`cog_unload(self)`).

2021-07-05 05:19 UTC, Injabie3 commented
Also [this](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Cog.cog_unload) for reference.

2021-07-05 05:55 UTC, tplamondon commented
Moved the thing to unload now, as well as added awaiting on typing so it doesn't look like the bot froze

2021-07-05 07:05 UTC, Injabie3 requested changes
I think this is going in the right direction. I saw the following, can we make a task instead and adding some logging?
```
[2021-07-04 23:40:54] [WARNING] py.warnings: /home/injabie3/github/Rin/lib/python3.8/site-packages/discord.py-1.7.3-py3.8.egg/discord/ext/commands/cog.py:451: RuntimeWarning: coroutine 'Source.__unload' was never awaited
  pass
```

2021-07-05 07:05 UTC, Injabie3 commented on cogs/source/source.py
> +    tracemoe = None
nit: unneeded
```suggestion
```

2021-07-05 07:05 UTC, Injabie3 commented on cogs/source/source.py
> +        asyncio.run(self.__unload())
Here we can create a task to close it instead:
```suggestion
        self.bot.loop.create_task(self.closeSession())
```

2021-07-05 07:05 UTC, Injabie3 commented on cogs/source/source.py
> +import asyncio
I don't think we'll need asyncio here, but we can actually use logging to help us debug:
```suggestion
import logging
```

2021-07-05 07:05 UTC, Injabie3 commented on cogs/source/source.py
> +        self.tracemoe = tracemoepy.AsyncTrace()
Can we save `bot here and use it to create task to close session later:
```suggestion
        self.bot = bot
        self.logger = logging.getLogger("red.eilacogs.Source")
        self.tracemoe = tracemoepy.AsyncTrace()
```

2021-07-05 07:05 UTC, Injabie3 commented on cogs/source/source.py
> +        await self.tracemoe.aio_session.close()
Let's not copy the function name from the other file; can we use a better name? Also add logging to help us double check that we end up here.
```suggestion
    async def closeSession(self):
        self.logger.debug("Closing session")
        await self.tracemoe.aio_session.close()
```

2021-07-06 03:21 UTC, tplamondon commented
> 
> 
> I think this is going in the right direction. I saw the following, can we make a task instead and adding some logging?
> 
> ```
> [2021-07-04 23:40:54] [WARNING] py.warnings: /home/injabie3/github/Rin/lib/python3.8/site-packages/discord.py-1.7.3-py3.8.egg/discord/ext/commands/cog.py:451: RuntimeWarning: coroutine 'Source.__unload' was never awaited
>   pass
> ```

Added in your suggestions

2021-07-06 03:38 UTC, Injabie3 approved these changes
LGTM

2021-07-06 03:38 UTC, Injabie3 commented on cogs/source/source.py
> -async def postSourceFunction(ctx, imageURL):
Note to self: we're moving it within the class since we declared single `tracemoepy.AsyncTrace` instance and are reusing it.

2021-07-06 03:38 UTC, Injabie3 commented on cogs/source/source.py
> +                # send the message using messageBGuilder to build the message
nit: comment typo
```suggestion
                # send the message using messageBuilder to build the message
```

2021-07-06 04:05 UTC, tplamondon commented
done I think

2021-07-06 04:17 UTC, merged