Small bugfix
SFUAnime/Ren pull request #472
Opened 2021-09-06 04:09 UTC by jlacsamana

[WordFilter] Add statistics for filtered words #280 
-reworked _wordfilter() to return message unmodified if filter list is empty

2021-09-06 05:08 UTC, Injabie3 requested changes
Thanks, can we remove the stuff that isn't related to the fix?

2021-09-06 05:08 UTC, Injabie3 commented on cogs/wordfilter/constants.py
> +}
nit: remove these changes from this PR.

2021-09-06 05:08 UTC, Injabie3 commented on cogs/wordfilter/wordfilter.py
> +from os import stat
Not needed.

2021-09-06 05:08 UTC, Injabie3 commented on cogs/wordfilter/wordfilter.py
> +
nit: remove whitespace change.

2021-09-06 05:08 UTC, Injabie3 commented on cogs/wordfilter/wordfilter.py
> +
nit: remove whitespace change.

2021-09-06 05:08 UTC, Injabie3 commented on cogs/wordfilter/wordfilter.py
> +
nit: remove whitespace change.

2021-09-06 05:08 UTC, Injabie3 commented on cogs/wordfilter/wordfilter.py
> +
Can we remove this change since it's not related to this issue?

2021-09-06 18:09 UTC, Injabie3 requested changes
One last thing

2021-09-06 18:09 UTC, Injabie3 commented on cogs/wordfilter/wordfilter.py
> -    return re.sub(regex, _censorMatch, string, flags=re.IGNORECASE)
What happened to this return?

2021-09-06 21:01 UTC, jlacsamana commented on cogs/wordfilter/wordfilter.py
> -    return re.sub(regex, _censorMatch, string, flags=re.IGNORECASE)
accidental delete when i was manually splitting the PRs lmaoo

2021-09-07 00:03 UTC, Injabie3 approved these changes
Thanks, LGTM

2021-09-07 00:08 UTC, merged