Quachtridat/issue515
SFUAnime/Ren pull request #520
Opened 2021-11-18 09:17 UTC by quachtridat

## Summary

As described in #515, this PR adds a toggle which lets `Welcome` cog posts the embed that is supposed to be sent to new users coming to a server, but was failed (e.g., due to users' privacy settings blocking DMs).

## Details

### New command

- `[p]welcomeset channelconfig postfaileddm`: toggle the behavior. Short aliases are also available.

### New `async` method `sendToWelcomeChannel()`

This method posts a Discord message to a guild's welcome channel and raises exceptions accordingly on error.

### Additional logic in `sendWelcomeMessages`

On failed DMs, if the behavior is enabled, call `sendToWelcomeChannel()` with a small message to notify the respective new users about the DM welcome embed.

### New constants

- `KEY_WELCOME_CHANNEL_SETTINGS`
- `KEY_POST_FAILED_DM`

## Linked issues

This resolves #515.

## Notes

Might need some discussion about the command group `channelconfig` and `KEY_WELCOME_CHANNEL_SETTINGS`. They are probably redundant now, but it seems that *posting failed DMs* is only a *welcome channel* thing, and perhaps having a group for welcome-channel-related configs would make subcommands more organized (e.g., `[p]welcomeset greetings` subcommands may manage greetings and `[p]welcomeset greetings channel` may become `[p]welcomeset channelconfig greetingchannel` instead.

2021-11-20 22:15 UTC, Injabie3 commented
Re: command group, I think we might want to restructure the commands/groups under `[p]welcomeset`. Originally we had it for welcome DMs only, but with further additions, the command layout has become a bit messy.

Perhaps we could do something like:
- [p]welcomeset
    - dm
        - message
        - title
        - image
        - test
        - toggle
    - log
        - channel
        - toggle
        - tag
            - add
            - get
            - list
            - remove
    - greetings
        - toggle
        - add
        - list
        - remove

Open to inputs here.

2021-11-27 07:27 UTC, quachtridat commented
> * [p]welcomeset
>   
>   * dm
>     
>     * message
>     * title
>     * image
>     * test
>     * toggle
>   * greetings
>     
>     * add
>     * list
>     * remove
>     * toggle
>   * log
>     
>     * channel
>     * tag
>       
>       * add
>       * get
>       * list
>       * remove
>     * toggle
>
> Open to inputs here.

Somehow I feel that `tag` and `log` would look better if there were at the same level. Also we need `[p]welcomeset greetings channel`. Everything else seems good to me.

Also if we opt in for `guildConfig[KEY_DM][KEY_MESSAGE]` (the nested `dict` way) we'll need to move stored things around as well.

2022-02-04 02:24 UTC, Injabie3 commented
Coming back to this, I think we should change the command hierarchy first in another PR, and then come back to this failed DM messaging thing after that's complete.

> Also we need `[p]welcomeset greetings` channel.

yep, thanks +1

> I feel that `tag` and `log` would look better if there were at the same level.

I'm indifferent, I put `tag` under `log` because tag uses the same "logging" channel.

2022-03-12 07:32 UTC, quachtridat commented
> Coming back to this, I think we should change the command hierarchy first in another PR, and then come back to this failed DM messaging thing after that's complete.
I agree.
> I'm indifferent, I put `tag` under `log` because tag uses the same "logging" channel.
I would want to think that `log` and `tag` should be at the same level because tagging/description assigning does not sound like a sub-feature of logging.

2022-05-22 06:22 UTC, Injabie3 commented
Any updates on this one?

2022-05-22 06:23 UTC, Injabie3 commented
Or were you waiting for me to review it again?

2022-05-22 06:28 UTC, quachtridat commented
> Any updates on this one?

Ah sorry, I haven't got a chance to make further changes. Anyway, this is what I am considering:

- `[p]welcomeset`
    - `dm`
        - `message`
        - `title`
        - `image`
        - `test`
        - `toggle`
    - `greetings`
        - `add`
        - `channel`
        - `list`
        - `remove`
        - `toggle`
    - `log`
        - `channel`
        - `toggle`
    - `tag`
        - `add`
        - `get`
        - `list`
        - `remove`

Will see if I can ready this PR within the coming week.

2022-06-11 16:30 UTC, Injabie3 requested changes
As per sideband discussion, will wait for manual re-test confirmation.

2022-06-11 16:30 UTC, Injabie3 commented on cogs/welcome/welcome.py
> +            If keyword arguments are invalid
Please add a docstring comment for `ValueError`

2022-06-13 08:09 UTC, quachtridat commented
> As per sideband discussion, will wait for manual re-test confirmation.

Re-tested @ https://discord.com/channels/800838291959447602/895950136688132137/985810413847461899.

2022-06-15 18:32 UTC, Injabie3 approved these changes

2022-06-15 18:37 UTC, Injabie3 commented
Will merge and cherry pick the squashed commit to the cog repo since welcome changes have diverged since the PR was opened.

2022-06-15 18:38 UTC, merged