[Misc] Simplify logging setup
SFUAnime/Ren pull request #560
Opened 2022-06-04 18:55 UTC by Injabie3

### Description of the changes
This PR fixes #511 by removing all explicit `logging.INFO` level configuration in favour of inheritting the one set by the bot. This way, it will allow the `--debug` flag to work as expected: showing the debug level on custom cogs.

Note:
The changes here will be rebased onto the target branch.

2022-06-04 23:25 UTC, quachtridat requested changes
Only one mistake in `cogs/respects.py`. The rest LGTM.

2022-06-04 23:25 UTC, quachtridat commented on cogs/respects/respects.py
> +        if not self.logging.handlers:
```suggestion
        if not self.logger.handlers:
```

2022-06-05 04:34 UTC, quachtridat approved these changes
LGTM.

2022-06-05 04:39 UTC, merged

2022-06-05 04:40 UTC, Injabie3 commented
Note: force push was to re-sign locally.