Prevent Ren from going over 1000 char
SFUAnime/Ren pull request #92
Opened 2018-09-02 23:54 UTC by zach1502

Pylint is gonna #rek me

### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
added if operator

2018-09-03 07:15 UTC, Injabie3 requested changes
Hey zach, some comments below.  Pylint will not complain right now, since this file is ignored at the moment.  Since this cog is small, please also remove `zalgo.py` from `pylintrc` to give you pylint results, and address those as needed.

2018-09-03 07:15 UTC, Injabie3 commented on cogs/zalgo.py
> +        def zalgoify(self, text, amount=3):
Why is this being indented?  The method call on line 41 will fail if this is like this.

2018-09-03 07:15 UTC, Injabie3 commented on cogs/zalgo.py
> +        list = ["Really? this is over 1000 letters long!", "Hmmm... Are you trying to launch a DOS attack?",
Let's just make the change as-is, no need for multiple messages in my opinion.

2018-09-03 07:15 UTC, Injabie3 commented on cogs/zalgo.py
> +        while len(text) >= 1000:
No need for a while loop, just do an if statement.

2018-09-03 07:15 UTC, Injabie3 commented on cogs/zalgo.py
> +            break
This break serves no purpose here: you'll still end up trying to send the message, where it'll error out.  Just `return` here and as I state above, change it to an `if` statement.

2018-09-03 07:15 UTC, Injabie3 commented on cogs/zalgo.py
> +# -----------------------------------------------------------------------------------------
Lines 54-56: no need for this comment since it's self documenting.

2018-09-03 07:15 UTC, Injabie3 commented on cogs/zalgo.py
> +            await self.bot.say(random.choice(list)) # noticed choice wasn't being used so i'm gonna use it
nit: No need to justify use of choice.

2018-09-03 09:11 UTC, zach1502 commented
```cogs/zalgo.py:56:23: W0622: Redefining built-in 'range' (redefined-builtin)
cogs/zalgo.py:50:4: R0201: Method could be a function (no-self-use)```
will fix ltr when i solve these ancient riddles

2018-09-03 18:36 UTC, Injabie3 requested changes
LGTM, just few minor things regarding docstrings/comments: let's keep them relevant please.

2018-09-03 18:36 UTC, Injabie3 commented on cogs/zalgo.py
> +'''pylint told me to put something here'''
Let's keep docstrings relevant: please describe what the cog does, or remove it if you've disabled pylint for this file.

2018-09-03 18:36 UTC, Injabie3 commented on cogs/zalgo.py
> +    '''pylint told me to do this'''
Same here.

2018-09-03 18:36 UTC, Injabie3 commented on cogs/zalgo.py
> +        '''pylint told me to do this, This will "zalgofy" your text :aquaThumbsUp:'''
Same here.  Also, no emojis here please, they add no value.

2018-09-03 18:36 UTC, Injabie3 commented on cogs/zalgo.py
> +        '''do i really need a docstring here pylint?'''
Same here.

2018-09-03 18:36 UTC, Injabie3 commented on cogs/zalgo.py
> +    '''do I really need a Docstring here?'''
Same here.  Just put something like ```"""Adding the cog to the bot."""```

2018-09-03 18:36 UTC, Injabie3 commented on cogs/zalgo.py
> +    # fekkin pylint
Please leave this out, and the following 3 lines.

2018-09-19 22:23 UTC, Injabie3 commented
How is this going?

2018-09-20 07:46 UTC, zach1502 commented
should be ok now

2018-09-20 21:47 UTC, Injabie3 requested changes
Hey zach.  LGTM, just address these last two things, thanks.

2018-09-20 21:47 UTC, Injabie3 commented on cogs/zalgo.py
> +
nit: Don't introduce new whitespace.

2018-09-20 21:47 UTC, Injabie3 commented on cogs/zalgo.py
> +    # fekkin pylint
I don't mind if you put it in a comment of your PR, but please don't include this, and the below as a comment here.

2018-09-27 17:57 UTC, Injabie3 commented
Remove the comments at the bottom as per last feedback, and we can merge this in.

2018-09-27 18:20 UTC, zach1502 commented
Ok

2018-09-27 18:45 UTC, Injabie3 approved these changes

2018-09-27 18:48 UTC, merged